### ISSUE TITLE
 Update letsencrypt_base_do parameters 

### ISSUE THREAD

**Issue by jmsantamaria** [ghomem/puppet_infrastructure#1]
we have at the moment:
- missing $do_api_token parameter, used in a template deployed inside the class
- domains defaulting to [“[solidangle.eu](http://solidangle.eu/)“], it should have no default in my opinion

**Comment by jmsantamaria** [comment]
PR: https://github.com/ghomem/puppet_infrastructure/pull/2

**Comment by ghomem** [comment]
PR approved and merged. Thank you @jmsantamaria.

**Comment by jmsantamaria** [comment]
Thanks a lot, closing issue.
