### ISSUE TITLE
Fix harmless warning on install script

### ISSUE THREAD

**Issue by ghomem** [ghomem/puppet_infrastructure#30]
There is a harmless error message when the installation is performed on a Ubuntu node:

![Screenshot_20240307_203520](https://github.com/ghomem/puppet_infrastructure/assets/3352900/22389104-bef0-4b38-ab88-305c8f344728)

**Comment by PrinceSalatyell** [comment]
Link to PR:
  * https://github.com/ghomem/puppet_infrastructure/pull/35
