### ISSUE TITLE
Add Docker Hello World class

### ISSUE THREAD

**Issue by ghomem** [ghomem/puppet_infrastructure#31]
Let's add a Docker Hello World class to describe how Docker can be used with puppet_infrastructure.

**Comment by PrinceSalatyell** [comment]
Link to PR:
  * https://github.com/ghomem/puppet_infrastructure/pull/33

**Comment by ghomem** [comment]
Sucessfully tested after merge.

**Comment by PrinceSalatyell** [comment]
This has been merged and tested.
